title: Notepad
url: https://raqib.me
remote_theme: oinam/oinam-jekyll

footer:
  custom: true
  credit: false
footer_custom: 'An ever Work-in-Progress effort by <a href="https://raqib.me">Rakib</a>.'

plugins:
  - jekyll-relative-links
